#!/usr/bin/env python3
"""
Mock vLLM Server — OpenAI-compatible API for testing.

Responds to /v1/chat/completions with echo/canned responses.
Supports streaming (SSE) and non-streaming modes.
Used to test Kivi, vLLM, and inhouse providers without burning real tokens.

Usage:
    python tests/mock_vllm_server.py          # runs on port 9999
    python tests/mock_vllm_server.py --port 8000
"""
import argparse
import json
import time
import uuid
import asyncio
from datetime import datetime

from fastapi import FastAPI, Request
from fastapi.responses import StreamingResponse, JSONResponse
import uvicorn

app = FastAPI(title="Mock vLLM Server")

MOCK_MODEL = "mock-model-v1"


def make_id():
    return f"chatcmpl-{uuid.uuid4().hex[:12]}"


def make_chunk(chat_id: str, content: str, finish_reason=None, model=MOCK_MODEL):
    return {
        "id": chat_id,
        "object": "chat.completions.chunk",
        "created": int(time.time()),
        "model": model,
        "choices": [{
            "index": 0,
            "delta": {"content": content} if content else {},
            "finish_reason": finish_reason,
        }],
    }


def make_tool_call_chunk(chat_id: str, tool_call: dict, finish_reason=None, model=MOCK_MODEL):
    return {
        "id": chat_id,
        "object": "chat.completions.chunk",
        "created": int(time.time()),
        "model": model,
        "choices": [{
            "index": 0,
            "delta": {"tool_calls": [tool_call]},
            "finish_reason": finish_reason,
        }],
    }


def generate_response(messages: list, tools: list | None = None) -> str:
    """Generate a mock response based on the last user message."""
    last_user = ""
    for msg in reversed(messages):
        if msg.get("role") == "user":
            content = msg.get("content", "")
            if isinstance(content, list):
                last_user = " ".join(c.get("text", "") for c in content if c.get("type") == "text")
            else:
                last_user = content
            break

    if not last_user:
        return "I'm a mock AI assistant. How can I help you?"

    # Generate contextual mock responses
    lower = last_user.lower()
    if "hello" in lower or "hi" in lower:
        return f"Hello! I'm the mock vLLM server. You said: '{last_user}'. I can simulate AI responses for testing."
    elif "list" in lower and "file" in lower:
        return "Here are the files in the current directory:\n- README.md\n- backend.py\n- index.html\n- requirements.txt"
    elif "weather" in lower:
        return "The weather is 72°F and sunny. (This is a mock response for testing.)"
    elif "code" in lower or "function" in lower or "write" in lower:
        return f"Here's a mock implementation:\n\n```python\ndef mock_function():\n    \"\"\"Generated by mock vLLM server.\"\"\"\n    return \"This is a test response for: {last_user[:50]}\"\n```"
    elif "error" in lower or "fail" in lower:
        return "I detected potential issues. Here's my analysis:\n1. Check error logs\n2. Verify configuration\n3. Run tests\n(Mock diagnostic response)"
    elif "plan" in lower:
        return "## Plan\n1. Analyze requirements\n2. Design solution\n3. Implement changes\n4. Test thoroughly\n5. Deploy\n(Mock planning response)"
    else:
        return (
            f"Mock response to: \"{last_user[:100]}\"\n\n"
            "I've processed your request. Here's my analysis:\n"
            "- Input received and understood\n"
            "- Processing complete\n"
            "- Ready for follow-up questions\n\n"
            "*(This is a mock vLLM server response for testing purposes)*"
        )


def should_use_tool(messages: list, tools: list | None) -> dict | None:
    """Decide if we should simulate a tool call."""
    if not tools:
        return None
    last_user = ""
    for msg in reversed(messages):
        if msg.get("role") == "user":
            last_user = msg.get("content", "")
            if isinstance(last_user, list):
                last_user = " ".join(c.get("text", "") for c in last_user if c.get("type") == "text")
            break

    lower = last_user.lower()
    for tool in tools:
        fn = tool.get("function", {})
        name = fn.get("name", "")
        if name.lower() in lower or any(kw in lower for kw in name.split("_")):
            return {
                "name": name,
                "arguments": json.dumps({"input": last_user[:100]}),
            }
    return None


@app.get("/v1/models")
async def list_models():
    return {
        "object": "list",
        "data": [
            {"id": MOCK_MODEL, "object": "model", "created": int(time.time()), "owned_by": "mock"},
            {"id": "mock-llama-8b", "object": "model", "created": int(time.time()), "owned_by": "mock"},
        ],
    }


@app.get("/health")
async def health():
    return {"status": "ok", "model": MOCK_MODEL, "mock": True}


@app.post("/v1/chat/completions")
async def chat_completions(request: Request):
    body = await request.json()
    messages = body.get("messages", [])
    stream = body.get("stream", False)
    model = body.get("model", MOCK_MODEL)
    tools = body.get("tools")

    chat_id = make_id()

    # Check if we should simulate a tool call
    tool_call = should_use_tool(messages, tools)

    if stream:
        async def stream_gen():
            if tool_call:
                # Stream tool call
                tc = {
                    "index": 0,
                    "id": f"call_{uuid.uuid4().hex[:8]}",
                    "type": "function",
                    "function": {"name": tool_call["name"], "arguments": ""},
                }
                yield f"data: {json.dumps(make_tool_call_chunk(chat_id, tc, model=model))}\n\n"
                await asyncio.sleep(0.05)

                # Stream arguments in chunks
                args = tool_call["arguments"]
                for i in range(0, len(args), 10):
                    chunk_tc = {"index": 0, "function": {"arguments": args[i:i+10]}}
                    yield f"data: {json.dumps(make_tool_call_chunk(chat_id, chunk_tc, model=model))}\n\n"
                    await asyncio.sleep(0.02)

                yield f"data: {json.dumps(make_chunk(chat_id, '', finish_reason='tool_calls', model=model))}\n\n"
            else:
                # Stream text response
                response = generate_response(messages, tools)
                words = response.split(" ")
                for i, word in enumerate(words):
                    token = word + (" " if i < len(words) - 1 else "")
                    yield f"data: {json.dumps(make_chunk(chat_id, token, model=model))}\n\n"
                    await asyncio.sleep(0.02)

                yield f"data: {json.dumps(make_chunk(chat_id, '', finish_reason='stop', model=model))}\n\n"
            yield "data: [DONE]\n\n"

        return StreamingResponse(stream_gen(), media_type="text/event-stream")
    else:
        # Non-streaming
        response_text = generate_response(messages, tools)
        result = {
            "id": chat_id,
            "object": "chat.completion",
            "created": int(time.time()),
            "model": model,
            "choices": [{
                "index": 0,
                "message": {"role": "assistant", "content": response_text},
                "finish_reason": "stop",
            }],
            "usage": {
                "prompt_tokens": sum(len(str(m.get("content", ""))) // 4 for m in messages),
                "completion_tokens": len(response_text) // 4,
                "total_tokens": sum(len(str(m.get("content", ""))) // 4 for m in messages) + len(response_text) // 4,
            },
        }
        return JSONResponse(result)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Mock vLLM Server")
    parser.add_argument("--port", type=int, default=9999, help="Port to listen on")
    parser.add_argument("--host", default="0.0.0.0", help="Host to bind to")
    args = parser.parse_args()

    print(f"🚀 Mock vLLM Server starting on http://{args.host}:{args.port}")
    print(f"   Model: {MOCK_MODEL}")
    print(f"   Endpoints: /v1/chat/completions, /v1/models, /health")
    uvicorn.run(app, host=args.host, port=args.port, log_level="info")
